### ISSUE TITLE
Sometimes wrong bool return values

### ISSUE THREAD

**Issue by JupiterRider** [ebitengine/purego#183]
Here is an example using Raylib:
```golang
package main

import (
	"fmt"

	rl "github.com/gen2brain/raylib-go/raylib"
)

func main() {
	rl.InitWindow(800, 450, "This is a title")
	defer rl.CloseWindow()

	rl.SetTargetFPS(60)

	for !rl.WindowShouldClose() {
		rl.BeginDrawing()

		rl.ClearBackground(rl.RayWhite)
		fileDropped := rl.IsFileDropped()
		rl.DrawText(fmt.Sprintf("File dropped: %t", fileDropped), 190, 200, 20, rl.DarkGray)
		lmbDown := rl.IsMouseButtonDown(rl.MouseLeftButton)
		rl.DrawText(fmt.Sprintf("Left mouse button: %t", lmbDown), 190, 240, 20, rl.DarkGray)

		rl.EndDrawing()
	}
}
```

It prints: 
```
File dropped: true
Left mouse button: true
```
Both values should be false instead.

When applying my change from pull request #181 , it works like expected. 

Other functions like `WindowShouldClose` aren't affected. I couldn't figure why this behaves like this.

**Comment by TotallyGamerJet** [comment]
Hmm. I'm wondering if you cast r1 to byte before doing the != 0 if it works. Can you test? I'm not near my computer rn.

**Comment by JupiterRider** [comment]
@TotallyGamerJet Yes, casting to a byte works!

**Comment by TotallyGamerJet** [comment]
Ok so here's what I think is happening. The C code is using the AX register to do some operations so there's some number in it. When it returns false the C code only zeros the least significant byte so the rest of the number is still there. When you cast to byte the not equal test only checks the least significant byte so it returns the correct value. This is the expected behavior.

Could you change your PR to do that cast? Then add a test that setups a callback that returns the uintptr that was causing issues. Then make a RegisterLib function that calls that callback but returns a bool. I hope that makes sense

**Comment by JupiterRider** [comment]
I changed the PR.

I don't know how to reproduce that behavior. I found this by accident.

**Comment by TotallyGamerJet** [comment]
The test should look like this:

```go
func TestRegisterLibFunc_Bool(t *testing.T) {
	// this callback recreates the state where the return register
	// contains other information but the least significant byte is false
	cbFalse := purego.NewCallback(func() uintptr {
		return 0x7F5948AE9A00
	})
	var runFalse func() bool
	purego.RegisterFunc(&runFalse, cbFalse)
	if runFalse() != false {
		t.Errorf("runFalse returned true expected false")
	}
}
```

**Comment by JupiterRider** [comment]
@TotallyGamerJet 
Ah ok! You mean a mock test.
I implemented it. Thanks ;)
