### ISSUE TITLE
Question: PureGo performs Better than CGo?

### ISSUE THREAD

**Issue by jgardona** [ebitengine/purego#202]
Hello, good afternoon

I would like to know if purego performs nicely. Remember that using cgo, the overhead in functions was huge.

**Comment by TotallyGamerJet** [comment]
Purego will not out-perform Cgo because it uses the same slow mechanism for calling into C code. The reason both are slow is because of the synchronization between the C runtime and Go runtime. This can only be fixed by the Go team. Purego is likely even slower than Cgo see #172 for a suggested fix using generics. However, I'd like to see MakeFunc's performance to be improved instead of using generics.
