### ISSUE TITLE
Can we have a string instead of SEL for `Send`?

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#86]
I think we have already discussed this, but I was wondering why we have SEL as the first argument of `Send`, not a string.

In most cases, uses make a SEL by `objc.RegisterName` at that place, so isn't this redundant? Sorry if you have already explained the reason.

@TotallyGamerJet

**Comment by TotallyGamerJet** [comment]
I think we did discuss it. I might be thinking of #59. There are two reasons I chose this way.

1. objc_msgSend takes SEL as it's second argument
2. objc.RegisterName always grabs the global objective-c lock

It might just pre-optimization to pass a SEL instead of doing the conversion inside of Send. However, if the objc.RegisterName is placed in a global variable then the lock is amortized across the entire running of the program. I admit that not every use of objc.RegisterName did I do that because while rewriting 100s of lines of code it's easier to write it inline instead of going to the top and adding the global. See [ebiten/ui_glfw_darwin.go](https://github.com/hajimehoshi/ebiten/blob/86fa9366f754416ffc3d88eb83698427a62ba738/internal/ui/ui_glfw_darwin.go#L276). I could go and fix that.

If we chose to take a string instead of SEL then we realize that there is lock contention in the objective-c runtime then we must cache it inside of Send. Wouldn't this too need a lock though?

I'm open to suggestions.

**Comment by hajimehoshi** [comment]
Sorry but I forgot about the cost of the lock. I'm fine if there is a comment about the cost of the lock.

**Comment by TotallyGamerJet** [comment]
I will send a PR!

**Comment by TotallyGamerJet** [comment]
Should the comment be on ID.Send or objc.RegisterName? or Both?

**Comment by hajimehoshi** [comment]
Both would be better.
