### ISSUE TITLE
How can I get a float64 value from ID?

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#87]
https://developer.apple.com/documentation/foundation/nsnumber/1414104-doublevalue?language=objc

Some method returns a double value, but how can I get a float64 value from ID that is returned from Send?

**Comment by TotallyGamerJet** [comment]
The issue is that Send's signature is: `func (id ID) Send(sel SEL, args ...interface{}) ID` but an Object can return anything. 

I have thought about this and was thinking of changing the signature to this: `func Send(id ID, set SEL, args ...any)[T any]`.
This would work since Send is just a wrapper around `purego.RegisterLibFunc` which supports float returns. 

Before we didn't have generics so I couldn't do it and now it's a breaking change since we are removing the ID.Send method and replacing it with a function. But perhaps, keep the method as a wrapper to the generic function? I think it would be best in the long run to move to this generic form.

**Comment by hajimehoshi** [comment]
I tend to be against the idea to use generics because

* Using a type parameter to avoid casting of returning type doesn't seem a regular usecase of generics. One thing is that this doesn't improve static type safety compared to casting.
* A method chain with `Send` seems a pretty common usecase.

**Comment by TotallyGamerJet** [comment]
It's less about avoiding a cast and instead about calling the right function. You need to tell RegisterLibFunc what the return type so it can grab it from the right register.

I think that keeping both the method and function variant is advisable since when chaining is necessary use the method and if a type that isn't a cast from ID is needed (like float) use the generic kind.

**Comment by hajimehoshi** [comment]
Oh I realized you suggested a function and a method. Hmm.

> You need to tell RegisterLibFunc what the return type so it can grab it from the right register.

Oh I see. Then that makes sense. So with this plan, will you be changing `RegisterLibFunc` to accept the type?

**Comment by TotallyGamerJet** [comment]
No, I was planning on just calling RegisterLibFunc twice. Once with a float return and the other with ID. And then perhaps a fallback for the eventual struct return. But that isn't supported by RegisterLibFunc at all.

**Comment by hajimehoshi** [comment]
OK. I think I understand (a type parameter is needed to define a function signature for `RegisterLibFunc`). If we need to try twice, doesn't `RegisterLibFunc` need to return an error or something?

(I'll reply tomorrow or later. Thank you for your hard work!)
