### ISSUE TITLE
How can I pass NSPoint to a method?

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#88]
https://developer.apple.com/documentation/appkit/nscursor/1524612-initwithimage

Currently, passing a struct via Send is not supported, right?

**Comment by TotallyGamerJet** [comment]
This is correct. struct arguments are not supported by Send since they aren't supported by RegisterLibFunc

**Comment by hajimehoshi** [comment]
For `NSPoint`, would passing X and Y as adjacent arguments work?

**Comment by TotallyGamerJet** [comment]
For the case of NSPoint that should work on amd64 ([see this](https://stackoverflow.com/questions/42411819/c-on-x86-64-when-are-structs-classes-passed-and-returned-in-registers)). As well as on amd64 [(see Sec. B - 3)](https://learn.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=msvc-170). Ignore the fact that is a Microsoft page. Windows arm64 uses the same calling convention as macOS.

[Godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMQAJlIOAMngMmABy7gBGmMQSPgAOqAqEtgzObh7epHEJNgIBQaEsEVFcPpaY1klCBEzEBCnunlwWmFbZDJXVBLkh4ZF6ClU1dWmN/R1d%2BYUSAJQWqK7EyOwc/cSu1gDUwULKqIEE6wCkAOwAQgcaAILr1%2Bvoc2H066oHAMxnlze3948Anq/vF2OABF/udAZcAG67dDrKiuBjILgQKF4GEAKlRpHWKPRQmwfixOPWGJYwCxKzW%2By2Oz26zieymh1OYOBLMh0NhqFQEEZxwBnwpG2pu0EdMOLyBTJOAA4AJyNdYAVgAbEdWW8wZ84QikYq9Vjii8sbKTViYlNQZdgRwZrROIreJ4OFpSKhOI51go5gtMIcvC8eKQCJobaQIEg0FhcIQSORKDR6Mw2JxA/xBCIxOwpDJBIoVOpnTp0gYjCBTMZzKVynYIA4hg1fAx0OMelFFRl4okBPW9JkuwwWwVeu2q612oMXPU%2Bs0ymOBp1At0h22LPOeyN54PJoqZl75otOIKqdsRfs%2BZqbndXA9fc8NR9L99fX974CjiDX2CidrEciORj0EJf88QJbF/zwUlyQIVYhRPWl6UEXlmStd82Qub8uR5KUL2uI9Njg0UYnFSU%2BTlBUVTVVDXy1eFfz1dt1kNY1TTpC1P3fUM7Q4B1SCdF03Q4D09x9P0Xi8Xhg0LKYZgAaxASQuAAOmVFTVLU1Sjn0ThJEdENXU4XgFD0SStBmOBYAjVAWBiOhIjjCA0Gs2yomQYBih8LAITwRYADU8EwAB3AB5GJGBTXgEwISIjIgMI9LCQJqh%2BcLSEcthBCChhaGSwtSCwFhDGAcRcvwYhZzwCFMCM3LMFUMpXCilK9maPTaDwMJiCS5wsD06CIPCmYqAMYAFD8wKQrC7gItkDNxGzNN5CUNQ9N0HwSxMMx9HaozIBmVAYlaarDO9A8uFte1dNygSnmlZUAFplUkdZgGQZBGK8RSvHWCBoyIYhRLOiSQ2k0gEEwJgsCiHlSDkrxFUUjREaR5HkekLidN4vSBMMkANCDYGwxgRAUCsmz6DICgHNJ5yUGqFhHrcrwvDxzzvMwMbgtCp1UzoKLiBiuLcoS5hiBywM0sYAhMuyvT8sK4qXVK8rKuql1avqxqpvIQQWtytqOq6jAlhdPqWAGvhhtG/zOcm1MZtEObpAWvNlty3RGnWstNv1nbof2w6DKaFoknsJt10bZtFwmXpGj7Vpw7jpItxjoPyoEcdaknYZU%2BrNpNyj1s%2BjXLOG1GGpk6KXcTvYLxzu4y7%2BM4dYLgAJQAWUe57Xvez7vt%2BkhRNroGpNkkAXheRTx6n6eZ60jgMb43hsYsXH8ZHufxMxq7A5Mm0Zkq/mQ8kIA%3D%3D) shows the same thing. 

Note though that doing so is flaky for anything unaligned or bigger than 16 bytes. The reason I had not added support yet is because you have to determine if it is passed in registers or as a pointer to the struct.

**Comment by hajimehoshi** [comment]
Thanks!

At the same time, `RegisterFunc` doesn't support returning structs yet. I read the implementation of `cursorPosition` but this was quite tricky...

**Comment by anhoder** [comment]
Is there any new progress on this? 
I've encountered the same issue and I'm attempting to retrieve [`currentTime`](https://developer.apple.com/documentation/avfoundation/avplayer/1390404-currenttime?language=objc) of `AVPlayer`.

**Comment by TotallyGamerJet** [comment]
There is a work around by using [NSInvocation](https://developer.apple.com/documentation/foundation/nsinvocation). That's what ebitengine does

**Comment by anhoder** [comment]
Thanks. It looks like what I want

**Comment by TotallyGamerJet** [comment]
No there hasn't been any work. If you are interested in tackling this a PR would be much appreciated.

As for solutions on macOS you can use NSInvocation as was mentioned earlier. Another cross platform solution is [libffi](https://github.com/libffi/libffi). I personally haven't used it but it should work to circumvent the lack of struct support in purego.

**Comment by ksil** [comment]
Appreciate the fast response! Libffi is a neat idea. A fast alternative may also be to write wrapper functions that only use raw pointers as arguments, but, of course, that somewhat circumvents a proper solution to this struct-passing problem...

**Comment by TotallyGamerJet** [comment]
Wrappers are another good solution. Of course adding support for structs would be the best.

**Comment by TotallyGamerJet** [comment]
For anyone looking for an example of NSInvocation here’s one that opens a window. https://go.dev/play/p/J7nKrpnG1CH

**Comment by JupiterRider** [comment]
@TotallyGamerJet @ksil 
Structures work on linux if the size not bigger then 64 bits.
If you pass them as argument, convert them into a uintptr like so:
```golang
clearBackground(*(*uintptr)(unsafe.Pointer(&color.RGBA{255, 255, 255, 255})))
```

If the function returns a struct bigger then 64 bits, pass a reference as first argument:
```golang
var texture Texture2D
loadTexture(uintptr(unsafe.Pointer(&texture)), "icon.png")
```

**Comment by TotallyGamerJet** [comment]
Sure that works for some cases but wouldn't everywhere especially arm64 where a struct with all the same field types that's less than or equal to 8 bytes is put into one register in reverse order. 

I'm currently working on proper struct support. Arm64 is looking pretty solid. My plan is to have it done by end of next week.
